#!/bin/bash -x
# musicDownloads_toMusicFolder - a script to organize my music.

cd /home/david/Downloads
#ls *mp3
#ls *.ogg
x="*mp3"
y="*.ogg"

mv *.ogg /home/david/Music/ogg
mv *.mp3/home/david/Music/mp3
